# Documentation :
# https://dependabot.com/docs/config-file/

# Validator for Dependabot config file
# https://dependabot.com/docs/config-file/validator/

version: 1

update_configs:
  - package_manager: "javascript"

    # Where to look for package manifests. Relative to the repository's root.
    directory: "/"

    # How often to check for non-security updates and when to create pull requests.
    # Security updates are always created as soon as possible (i.e., "live").
    update_schedule: "monthly"

    # How to update manifest version requirements.
    # "auto" => version requirements increased if it's an app / range widened if it's a library.
    version_requirement_updates: "auto"

    # Format of commit messages and pull request titles.
    commit_message:
      prefix: "build"
      include_scope: true

    # Reviewers to set on pull requests
    default_reviewers:
      - "peopledoc/tribe-js"

    # Limit which updates are allowed
    allowed_updates:
      - match:
          update_type: "all" # all updates including indirect/sub-dependencies

    ignored_updates:
    - match:
        # Ignore updates of `ember-cli` as we want to take care of these by ourselves
        dependency_name: "ember-cli"
